# Generated by Django 4.2.20 on 2025-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='category',
            field=models.CharField(choices=[('IPHONESERIES', 'iPhone Series'), ('IPAD', 'iPad'), ('MACBOOKSERIES', 'Macbook Series')], max_length=20),
        ),
    ]
