# Generated by Django 4.2.20 on 2025-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_apple_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
